<?php

namespace App\Services;

use App\Enums\DepartmentReportType;
use App\Enums\DepartmentSpecialRole;
use App\Enums\UserStatus;
use App\Exceptions\DepartmentReportException;
use App\Models\Department;
use App\Models\DepartmentDailyReport;
use App\Models\DepartmentReportContribution;
use App\Models\TaskStatusHistory;
use App\Models\User;
use Illuminate\Database\QueryException;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Log;

/**
 * Daily Department Reports (product decision 2026-08). One "summary" report per active
 * department per day, auto-filled from that day's task_status_history and generated by
 * the agencyos:generate-daily-department-reports schedule at 15:30 Africa/Cairo; Content
 * additionally gets a second, blank "moderator_handoff" report addressed to whichever
 * department has special_role=moderator. The only writer of department_daily_reports.
 */
class DepartmentReportService
{
    /** The single daily generation time (Africa/Cairo), shared by the schedule entry
     *  in routes/console.php and DepartmentReportController's "not generated yet" state.
     *  Product decision 2026-09: pushed from 15:00 to 15:30, and every department's
     *  submission window now runs through midnight (see deadlineFor()) — previously
     *  only Photography/Videography had that extended window, everyone else was 20:00. */
    public const GENERATION_TIME = '15:30';

    public function __construct(
        private readonly NotificationService $notifications,
        private readonly AuditService $audit,
    ) {}

    public function generateForToday(): void
    {
        $today = now()->toDateString();

        $historyByDepartment = TaskStatusHistory::query()
            ->with(['changedBy:id,full_name', 'task:id,task_code,title'])
            ->whereDate('created_at', $today)
            ->get()
            ->groupBy('department_id');

        $departments = Department::where('is_active', true)
            ->with('leadershipAssignments.user')
            ->get();

        foreach ($departments as $department) {
            $this->generateReport(
                $department,
                DepartmentReportType::Summary,
                $today,
                $this->buildAutoSummary($department, $historyByDepartment),
            );
        }

        $content = $departments->first(fn (Department $d) => $d->special_role === DepartmentSpecialRole::Content);

        if ($content === null) {
            Log::warning('Daily department reports: no department with special_role=content found; skipping the Moderator handoff report.');

            return;
        }

        $this->generateReport($content, DepartmentReportType::ModeratorHandoff, $today, null);
    }

    /** @return array<int, array{user_id: int, user_name: string, task_id: int, task_code: ?string, task_title: ?string, event_types: array<int, string>}> */
    public function buildAutoSummary(Department $department, Collection $historyByDepartment): array
    {
        $rows = $historyByDepartment->get($department->id, collect())
            ->filter(fn (TaskStatusHistory $h) => $h->changed_by !== null && $h->task_id !== null);

        return $rows->groupBy(fn (TaskStatusHistory $h) => $h->changed_by.'-'.$h->task_id)
            ->map(function (Collection $group): array {
                $first = $group->first();

                return [
                    'user_id' => $first->changed_by,
                    'user_name' => $first->changedBy?->full_name ?? '—',
                    'task_id' => $first->task_id,
                    'task_code' => $first->task?->task_code,
                    'task_title' => $first->task?->title,
                    'event_types' => $group->pluck('event_type')
                        ->map(fn ($event) => $event->value)
                        ->unique()
                        ->values()
                        ->all(),
                ];
            })
            ->values()
            ->all();
    }

    /**
     * Product decision 2026-09: every department's submission window now runs through
     * midnight — previously only Photography/Videography (special_role) had this
     * extended deadline, everyone else was 20:00. $department is kept in the signature
     * even though it's now unused here (every caller already has it in hand, and other
     * DepartmentSpecialRole cases may need a department-specific deadline again later).
     */
    public function deadlineFor(Department $department, string $reportDate): Carbon
    {
        return Carbon::parse($reportDate)->endOfDay();
    }

    /**
     * @param  array<int|string, ?string>  $taskComments  task_id => comment, from the
     *                                                    TL's per-task comment form
     *                                                    next to that day's activity
     *                                                    table (product decision 2026-09).
     */
    public function submit(DepartmentDailyReport $report, User $actor, string $details, array $taskComments = [], ?string $externalNote = null): DepartmentDailyReport
    {
        Gate::forUser($actor)->authorize('submit', $report);

        if ($report->isSubmitted()) {
            throw DepartmentReportException::alreadySubmitted();
        }

        $now = now();
        $isLate = $now->gt($this->deadlineFor($report->department, $report->report_date->toDateString()));

        // Sales writes collectively (product decision 2026-09): the submitted text is
        // built here from the members' own parts, so whatever the form posted is
        // ignored. The Team Leader submits the report; they do not author it, and
        // nothing they can type reaches another person's words.
        if ($this->collectsMemberReports($report)) {
            $details = $this->composeDetails($report);
        }

        $report->forceFill([
            'details' => $details,
            'task_comments' => $this->sanitizeTaskComments($taskComments),
            'external_note' => $this->sanitizeNote($externalNote),
            'submitted_at' => $now,
            'submitted_by' => $actor->id,
            'is_late' => $isLate,
        ])->save();

        $this->audit->log(
            action: 'department_report.submitted',
            entityType: 'department_report',
            entityId: $report->id,
            after: ['submitted_at' => $now->toIso8601String(), 'is_late' => $isLate],
            actorId: $actor->id,
        );

        return $report;
    }

    /** Correcting the text after submission — submitted_at/is_late stay put, since those
     *  are historical facts about the original submission, not about this edit. */
    public function update(DepartmentDailyReport $report, User $actor, string $details, array $taskComments = [], ?string $externalNote = null): DepartmentDailyReport
    {
        Gate::forUser($actor)->authorize('update', $report);

        if (! $report->isSubmitted()) {
            throw DepartmentReportException::notYetSubmitted();
        }

        if ($this->collectsMemberReports($report)) {
            $details = $this->composeDetails($report);
        }

        $before = $report->details;
        $report->forceFill([
            'details' => $details,
            'task_comments' => $this->sanitizeTaskComments($taskComments),
            'external_note' => $this->sanitizeNote($externalNote),
        ])->save();

        $this->audit->log(
            action: 'department_report.edited',
            entityType: 'department_report',
            entityId: $report->id,
            before: ['details' => $before],
            after: ['details' => $details],
            actorId: $actor->id,
        );

        return $report;
    }

    // ------------------------------------------------- collective reports (Sales)

    /**
     * Whether this report is written by the whole department instead of by its Team
     * Leader alone (product decision 2026-09 — Sales). Only the daily summary works
     * this way; the Moderator handoff stays a single-author note.
     */
    public function collectsMemberReports(DepartmentDailyReport $report): bool
    {
        return $report->type === DepartmentReportType::Summary
            && $this->departmentCollectsMemberReports($report->department);
    }

    /**
     * The same question asked of a department rather than of one of its reports — the
     * member-facing screen has to answer "does my team work this way?" before today's
     * report exists at all, and before the generation run has happened.
     */
    public function departmentCollectsMemberReports(?Department $department): bool
    {
        return $department?->special_role === DepartmentSpecialRole::Sales;
    }

    /**
     * Everyone expected to write a part: the department's active staff, Team Leader
     * included — they are a member of their own team, not an editor sitting above it.
     *
     * @return Collection<int, User>
     */
    public function membersFor(Department $department): Collection
    {
        return User::query()
            ->where('department_id', $department->id)
            ->where('status', UserStatus::Active->value)
            ->orderBy('full_name')
            ->get(['id', 'full_name']);
    }

    /**
     * Save (or replace) one person's own part. They may keep editing it right up until
     * the report is submitted, and never after — at that point the words are already in
     * front of the Manager.
     */
    public function contribute(DepartmentDailyReport $report, User $actor, string $body): DepartmentReportContribution
    {
        Gate::forUser($actor)->authorize('contribute', $report);

        if ($report->isSubmitted()) {
            throw DepartmentReportException::alreadySubmitted();
        }

        $existing = DepartmentReportContribution::where('report_id', $report->id)
            ->where('user_id', $actor->id)
            ->first();

        $contribution = DepartmentReportContribution::updateOrCreate(
            ['report_id' => $report->id, 'user_id' => $actor->id],
            [
                'body' => trim($body),
                'submitted_at' => $existing?->submitted_at ?? now(),
                'updated_at' => $existing !== null ? now() : null,
            ],
        );

        $this->audit->log(
            action: 'department_report.contributed',
            entityType: 'department_report',
            entityId: $report->id,
            after: ['user_id' => $actor->id, 'contribution_id' => $contribution->id],
            actorId: $actor->id,
        );

        return $contribution;
    }

    /**
     * The one report, built from the parts. Each person's text is copied EXACTLY as
     * they typed it — the only thing added is their name above it, and a line for
     * anyone who did not write (asked for 2026-09: the Manager sees who was missing
     * rather than have them quietly disappear).
     *
     * Order is by name, so the same report never reshuffles itself between renders.
     */
    public function composeDetails(DepartmentDailyReport $report): string
    {
        $contributions = DepartmentReportContribution::where('report_id', $report->id)
            ->get()
            ->keyBy('user_id');

        return $this->membersFor($report->department)
            ->map(function (User $member) use ($contributions): string {
                $body = $contributions->get($member->id)?->body;

                return '─ '.$member->full_name." ─\n".
                    ($body ?? __('agencyos.department_reports.contributions.did_not_write'));
            })
            ->implode("\n\n");
    }

    /**
     * Who has written and who has not, for the checklist above the submit button.
     *
     * @return array{members: Collection<int, User>, written: Collection<int, DepartmentReportContribution>, missing: Collection<int, User>}
     */
    public function contributionStatus(DepartmentDailyReport $report): array
    {
        $members = $this->membersFor($report->department);
        $written = DepartmentReportContribution::where('report_id', $report->id)
            ->with('user:id,full_name')
            ->get()
            ->keyBy('user_id');

        return [
            'members' => $members,
            'written' => $written,
            'missing' => $members->reject(fn (User $m) => $written->has($m->id))->values(),
        ];
    }

    /** @param  array<int|string, ?string>  $raw
     *  @return array<int, string> */
    private function sanitizeTaskComments(array $raw): array
    {
        $comments = [];

        foreach ($raw as $taskId => $comment) {
            $trimmed = trim((string) $comment);

            if ($trimmed !== '') {
                $comments[(int) $taskId] = $trimmed;
            }
        }

        return $comments;
    }

    private function sanitizeNote(?string $note): ?string
    {
        $trimmed = trim((string) $note);

        return $trimmed === '' ? null : $trimmed;
    }

    /**
     * Product decision 2026-09 — a Manager approves each submitted report individually.
     * Approval is what makes the report visible to the Moderator beyond its own
     * department (DepartmentDailyReport::scopeVisibleTo()), on top of the Content
     * handoff report they already see.
     */
    public function approve(DepartmentDailyReport $report, User $actor): DepartmentDailyReport
    {
        Gate::forUser($actor)->authorize('approve', $report);

        if (! $report->isSubmitted()) {
            throw DepartmentReportException::notYetSubmitted();
        }

        if ($report->isApproved()) {
            throw DepartmentReportException::alreadyApproved();
        }

        $now = now();

        $report->forceFill([
            'approved_at' => $now,
            'approved_by' => $actor->id,
        ])->save();

        $this->audit->log(
            action: 'department_report.approved',
            entityType: 'department_report',
            entityId: $report->id,
            after: ['approved_at' => $now->toIso8601String()],
            actorId: $actor->id,
        );

        return $report;
    }

    /** firstOrCreate() keyed on the table's own unique index is the concurrency guard —
     *  a concurrent manual run just hits the constraint and refetches instead of
     *  duplicating. wasRecentlyCreated skips renotifying on an idempotent re-run. */
    private function generateReport(Department $department, DepartmentReportType $type, string $date, ?array $autoSummary): void
    {
        try {
            $report = DepartmentDailyReport::firstOrCreate(
                ['department_id' => $department->id, 'report_date' => $date, 'type' => $type->value],
                ['auto_summary' => $autoSummary],
            );
        } catch (QueryException) {
            $report = DepartmentDailyReport::query()
                ->where('department_id', $department->id)
                ->where('report_date', $date)
                ->where('type', $type->value)
                ->first();

            if ($report === null) {
                return;
            }
        }

        if (! $report->wasRecentlyCreated) {
            return;
        }

        $leader = $department->effectiveLeader();

        if ($leader === null) {
            return;
        }

        $this->notifications->notify(
            $leader,
            'department_report.ready',
            __('agencyos.department_reports.notifications.ready_title'),
            __('agencyos.department_reports.notifications.ready_body', ['department' => $department->name]),
            'department_report',
            $report->id,
        );
    }
}
